version: '3.7'

services:

  biotrace-frontend-dev:
    container_name: biotrace-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
