export interface AuthState {
  loadingSignInRequest: boolean;
  loadingSignUpRequest: boolean;
  loadingForgotPasswordRequest: boolean;
  loadingVerifyCodeRequest: boolean;
  loadingChangePasswordRequest: boolean;
  msgSignUp: string;
  signUpError: boolean;
  signInError: boolean;
  forgotPasswordError: boolean;
  verifyCodeError: boolean;
  changePasswordError: boolean;
  email: string;
  emailForgotPassword: string;
  stepForgotPassword: string;
  code: string;
  newPassword: string;
  resultChangePassword: boolean;
  password: string;
  companyEmail: string;
  companyName: string;
  companyAddress: string;
  companyZipCode: string;
  companyNif: string;
  companyPhone: string;
  companyFunction: string;
  token: string;
  isSignedIn: boolean;
}
